#include <math.h>

// ============================================================
// KNEVO ULTRA SMOOTH FSM + CLINICAL TRAJECTORY + MOTOR OUTPUT
// ------------------------------------------------------------
// This version further reduces the "tak tak" / stop-go motion problem.
// Main changes:
// 1) FSM states are still status only.
// 2) Desired angle is generated by cubic Hermite interpolation, not linear.
// 3) Motor receives a small look-ahead target, so it follows a moving target.
// 4) Motor command streaming is faster: 10 ms / 100 Hz.
// 5) A command smoothing filter removes small target jumps.
// 6) Actual-angle feedback is read less often so it does not interrupt motion.
// 7) ROM scaling keeps the same gait shape inside patient ROM.
// 8) ML/gait_percent bad reading logic remains: predict <=3, then freeze.
// ============================================================

#define MOTOR_RX_PIN 4
#define MOTOR_TX_PIN 5
#define BUZZER_PIN   13     // Change if your buzzer uses another GPIO

HardwareSerial MotorSerial(1);

// ============================================================
// MOTOR CALIBRATION / SESSION SETTINGS
// ============================================================
const float MOTOR_SCALE = 3722.0f;   // your approved calibration: physical deg -> raw

// Doctor/session ROM. Change this per patient/session.
// Example: set 40.0f if doctor says max knee flexion should be 40 degrees.
float THERAPIST_MAX_ROM_DEG = 65.0f;

// Normal clinical reference range used for preserving gait shape.
const float NORMAL_ROM_MIN_DEG = 5.0f;
const float NORMAL_ROM_MAX_DEG = 65.0f;

// ============================================================
// SMOOTH MOTION SETTINGS
// ============================================================
const unsigned long CONTROL_MS  = 10;   // stream motor target every 10 ms = 100 Hz
const unsigned long PLOT_MS     = 50;   // serial plotter update
const unsigned long FEEDBACK_MS = 250;  // actual angle read slower to avoid blocking motion

const float LOOKAHEAD_PERCENT = 4.0f;      // bigger look-ahead = less stop-go behavior
const float COMMAND_SMOOTH_ALPHA = 0.18f;  // 0.10 smoother/slower, 0.30 faster/less smooth

// Simulated gait input, same idea as old code but smoother with time.
// 8% per second means one full gait cycle takes about 12.5 seconds.
const float SIM_GAIT_SPEED_PERCENT_PER_SEC = 8.0f;

// ML / gait_percent plausibility.
const float MAX_GAIT_JUMP_PERCENT = 10.0f;
const int   MAX_BAD_READINGS      = 3;

// Scenario 2B emergency collapse threshold.
const float COLLAPSE_ERROR_DEG = 20.0f;

// ============================================================
// MOTOR COMMANDS
// ============================================================
uint8_t cmdOn[5] = {0x3E, 0x88, 0x01, 0x00, 0xC7};

// ============================================================
// FSM PHASE TABLE: STATUS ONLY
// ============================================================
struct FSMState {
  int id;
  float gpStart;
  float gpEnd;
  const char* name;
};

const FSMState fsmTable[6] = {
  {1,  0.0f,   5.0f,  "HeelStrike"       },
  {2,  5.0f,  15.0f,  "LoadingResponse"  },
  {3, 15.0f,  50.0f,  "MidTerminalStance"},
  {4, 50.0f,  62.0f,  "PreSwingToeOff"   },
  {5, 62.0f,  87.0f,  "InitialMidSwing"  },
  {6, 87.0f, 100.0f,  "TerminalSwing"    }
};

// ============================================================
// CLINICAL KNEE ANGLE TABLE
// The table is used for smooth desired angle generation.
// The 6 FSM states do NOT directly decide the angle.
// ============================================================
const int TRAJ_SIZE = 11;
const float gaitTable[TRAJ_SIZE] = {
  0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
};

const float kneeTable[TRAJ_SIZE] = {
  3.97, 19.84, 18.86, 11.09, 7.72, 13.86, 38.74, 64.12, 53.27, 17.27, 2.21
};

// ============================================================
// RUNTIME VARIABLES
// ============================================================
float Gait_percent = 0.0f;
float rawMLGaitPercent = 0.0f;
float usedGaitPercent = 0.0f;
float lookAheadGaitPercent = 0.0f;

float lastValidGaitPercent = 0.0f;
float predictedGaitPercent = 0.0f;
float gaitRatePerUpdate = 0.2f;

bool hasFirstValidGait = false;
bool badReading = false;
bool systemFrozen = false;
bool commandFilterReady = false;

int badReadingCounter = 0;
int statusCode = 1;
int supportMode = 0;  // 0 normal, 1 stance support, 2 emergency freeze

float desiredAngleNormal = 5.0f;
float desiredAngleROM = 5.0f;     // unfiltered target after ROM scaling
float commandedAngle = 5.0f;      // filtered motor command sent to motor
float actualAngle = 0.0f;
float lastSentAngle = -999.0f;
float frozenAngle = 5.0f;

unsigned long lastControlTime = 0;
unsigned long lastPlotTime = 0;
unsigned long lastFeedbackTime = 0;
unsigned long lastGaitUpdateTime = 0;

// ============================================================
// BASIC UTILITIES
// ============================================================
float wrapGaitPercent(float gp) {
  while (gp >= 100.0f) gp -= 100.0f;
  while (gp < 0.0f)    gp += 100.0f;
  return gp;
}

float gaitForwardDiff(float fromGp, float toGp) {
  float diff = toGp - fromGp;
  if (diff < -50.0f) diff += 100.0f;  // normal cycle wrap: 98 -> 2 = +4
  return diff;
}

float clampFloat(float x, float lo, float hi) {
  if (x < lo) return lo;
  if (x > hi) return hi;
  return x;
}

// ============================================================
// SMOOTH CUBIC HERMITE INTERPOLATION
// This removes the sharp velocity changes caused by linear interpolation.
// ============================================================
float tableSlope(int i) {
  if (i <= 0) {
    return (kneeTable[1] - kneeTable[0]) / (gaitTable[1] - gaitTable[0]);
  }

  if (i >= TRAJ_SIZE - 1) {
    return (kneeTable[TRAJ_SIZE - 1] - kneeTable[TRAJ_SIZE - 2]) /
           (gaitTable[TRAJ_SIZE - 1] - gaitTable[TRAJ_SIZE - 2]);
  }

  return (kneeTable[i + 1] - kneeTable[i - 1]) /
         (gaitTable[i + 1] - gaitTable[i - 1]);
}

float smoothClinicalAngle(float gp) {
  gp = clampFloat(gp, 0.0f, 100.0f);

  if (gp <= gaitTable[0]) return kneeTable[0];
  if (gp >= gaitTable[TRAJ_SIZE - 1]) return kneeTable[TRAJ_SIZE - 1];

  for (int i = 0; i < TRAJ_SIZE - 1; i++) {
    if (gp >= gaitTable[i] && gp <= gaitTable[i + 1]) {
      float x0 = gaitTable[i];
      float x1 = gaitTable[i + 1];
      float y0 = kneeTable[i];
      float y1 = kneeTable[i + 1];
      float m0 = tableSlope(i);
      float m1 = tableSlope(i + 1);

      float dx = x1 - x0;
      float t = (gp - x0) / dx;
      float t2 = t * t;
      float t3 = t2 * t;

      float h00 =  2.0f * t3 - 3.0f * t2 + 1.0f;
      float h10 =        t3 - 2.0f * t2 + t;
      float h01 = -2.0f * t3 + 3.0f * t2;
      float h11 =        t3 -       t2;

      float y = h00 * y0 + h10 * dx * m0 + h01 * y1 + h11 * dx * m1;

      // Keep normal clinical curve inside safe expected normal bounds.
      y = clampFloat(y, 0.0f, NORMAL_ROM_MAX_DEG);
      return y;
    }
  }

  return kneeTable[0];
}

// ============================================================
// ROM SCALING THAT PRESERVES GAIT SHAPE
// Example: normal 5..65 becomes patient 5..40, but keeps same curve shape.
// ============================================================
float scaleAngleToPatientROM(float normalAngle) {
  float maxROM = THERAPIST_MAX_ROM_DEG;

  if (maxROM < NORMAL_ROM_MIN_DEG) {
    maxROM = NORMAL_ROM_MIN_DEG;
  }

  float angleForScaling = normalAngle;
  if (angleForScaling < NORMAL_ROM_MIN_DEG) {
    angleForScaling = NORMAL_ROM_MIN_DEG;
  }

  float scaled = NORMAL_ROM_MIN_DEG +
                 (angleForScaling - NORMAL_ROM_MIN_DEG) *
                 (maxROM - NORMAL_ROM_MIN_DEG) /
                 (NORMAL_ROM_MAX_DEG - NORMAL_ROM_MIN_DEG);

  return clampFloat(scaled, NORMAL_ROM_MIN_DEG, maxROM);
}

// ============================================================
// FSM STATUS
// ============================================================
int getFSMStatusCode(float gp) {
  gp = clampFloat(gp, 0.0f, 100.0f);

  for (int i = 0; i < 6; i++) {
    if (i < 5) {
      if (gp >= fsmTable[i].gpStart && gp < fsmTable[i].gpEnd) {
        return fsmTable[i].id;
      }
    } else {
      if (gp >= fsmTable[i].gpStart && gp <= fsmTable[i].gpEnd) {
        return fsmTable[i].id;
      }
    }
  }

  return 6;
}

bool isStanceSupportState(int stateId) {
  // Normal support, not a hard stop.
  // The trajectory still moves smoothly; this only reports support mode.
  return (stateId == 2 || stateId == 3);
}

// ============================================================
// BUZZER / FREEZE
// ============================================================
void buzzerOn() {
  digitalWrite(BUZZER_PIN, HIGH);
}

void buzzerOff() {
  digitalWrite(BUZZER_PIN, LOW);
}

void freezeSystem(int emergencyMode) {
  systemFrozen = true;
  supportMode = emergencyMode;
  frozenAngle = commandedAngle;
  buzzerOn();
}

// ============================================================
// MOTOR FUNCTIONS
// ============================================================
void sendCmd(uint8_t* cmd, int len) {
  while (MotorSerial.available()) MotorSerial.read();
  MotorSerial.write(cmd, len);
  MotorSerial.flush();
}

bool motorOn() {
  for (int attempt = 0; attempt < 20; attempt++) {
    while (MotorSerial.available()) MotorSerial.read();
    sendCmd(cmdOn, 5);
    delay(200);

    uint8_t buf[16];
    int n = 0;
    unsigned long t = millis();

    while (n < 16 && millis() - t < 200) {
      if (MotorSerial.available()) {
        buf[n++] = MotorSerial.read();
        t = millis();
      }
    }

    for (int i = 0; i < n; i++) {
      if (buf[i] == 0x3E) return true;
    }

    delay(100);
  }

  return false;
}

void sendPositionFast(float outputDeg) {
  int32_t angleRaw = (int32_t)(outputDeg * MOTOR_SCALE);

  uint8_t buf[14];
  buf[0]  = 0x3E;
  buf[1]  = 0xA3;
  buf[2]  = 0x01;
  buf[3]  = 0x08;
  buf[4]  = (0x3E + 0xA3 + 0x01 + 0x08) & 0xFF;
  buf[5]  = angleRaw & 0xFF;
  buf[6]  = (angleRaw >> 8)  & 0xFF;
  buf[7]  = (angleRaw >> 16) & 0xFF;
  buf[8]  = (angleRaw >> 24) & 0xFF;
  buf[9]  = 0x00;
  buf[10] = 0x00;
  buf[11] = 0x00;
  buf[12] = 0x00;

  uint8_t sum = 0;
  for (int i = 5; i < 13; i++) sum += buf[i];
  buf[13] = sum & 0xFF;

  // No delay here. This avoids stop-go behavior.
  sendCmd(buf, 14);
}

float readActualAngleQuick() {
  uint8_t angleCmd[5] = {0x3E, 0x92, 0x01, 0x00, 0xD1};

  while (MotorSerial.available()) MotorSerial.read();
  MotorSerial.write(angleCmd, 5);
  MotorSerial.flush();

  uint8_t rx[32];
  int n = 0;
  unsigned long t = millis();

  // Short timeout so feedback does not interrupt smooth motion.
  while (n < 32 && millis() - t < 30) {
    if (MotorSerial.available()) {
      rx[n++] = MotorSerial.read();
      t = millis();
    }
  }

  for (int i = 0; i < n - 8; i++) {
    if (rx[i] == 0x3E && rx[i + 1] == 0x92) {
      uint32_t rawUnsigned =
        ((uint32_t)rx[i + 5]) |
        ((uint32_t)rx[i + 6] << 8) |
        ((uint32_t)rx[i + 7] << 16) |
        ((uint32_t)rx[i + 8] << 24);

      int32_t rawAngle = (int32_t)rawUnsigned;
      return (float)rawAngle / MOTOR_SCALE;
    }
  }

  return actualAngle;
}

// ============================================================
// GAIT INPUT + VALIDATION
// ============================================================
float getGaitPercentInput() {
  // Same old idea: simulated gait input.
  // Later replace only this function with ML output.
  unsigned long now = millis();

  if (lastGaitUpdateTime == 0) {
    lastGaitUpdateTime = now;
    return Gait_percent;
  }

  float dt = (now - lastGaitUpdateTime) / 1000.0f;
  lastGaitUpdateTime = now;

  float step = SIM_GAIT_SPEED_PERCENT_PER_SEC * dt;
  Gait_percent = wrapGaitPercent(Gait_percent + step);

  return Gait_percent;
}

float validateOrPredictGait(float newGaitPercent) {
  newGaitPercent = clampFloat(newGaitPercent, 0.0f, 100.0f);

  if (!hasFirstValidGait) {
    hasFirstValidGait = true;
    badReading = false;
    badReadingCounter = 0;
    lastValidGaitPercent = newGaitPercent;
    predictedGaitPercent = newGaitPercent;
    return newGaitPercent;
  }

  float jump = gaitForwardDiff(lastValidGaitPercent, newGaitPercent);
  bool validForwardMotion = (jump >= 0.0f && jump <= MAX_GAIT_JUMP_PERCENT);

  if (validForwardMotion) {
    badReading = false;
    badReadingCounter = 0;

    if (jump > 0.0f && jump < MAX_GAIT_JUMP_PERCENT) {
      gaitRatePerUpdate = jump;
    }

    lastValidGaitPercent = newGaitPercent;
    predictedGaitPercent = newGaitPercent;
    return newGaitPercent;
  }

  // Invalid ML/gait reading: continue short prediction.
  badReading = true;
  badReadingCounter++;

  predictedGaitPercent = wrapGaitPercent(predictedGaitPercent + gaitRatePerUpdate);

  if (badReadingCounter > MAX_BAD_READINGS) {
    freezeSystem(2);
  }

  return predictedGaitPercent;
}

// ============================================================
// TRAJECTORY UPDATE
// ============================================================
void updateSmoothFSMAndTrajectory(float gp) {
  statusCode = getFSMStatusCode(gp);

  if (isStanceSupportState(statusCode)) {
    supportMode = 1;
  } else {
    supportMode = 0;
  }

  // Look-ahead makes the motor chase a moving future target instead of
  // reaching one tiny target and stopping at it.
  lookAheadGaitPercent = wrapGaitPercent(gp + LOOKAHEAD_PERCENT);

  desiredAngleNormal = smoothClinicalAngle(lookAheadGaitPercent);
  desiredAngleROM = scaleAngleToPatientROM(desiredAngleNormal);

  // Extra smoothing layer:
  // The clinical target may still change in small steps.
  // This filter makes the command angle glide instead of jumping.
  if (!commandFilterReady) {
    commandedAngle = desiredAngleROM;
    commandFilterReady = true;
  } else {
    commandedAngle = commandedAngle + COMMAND_SMOOTH_ALPHA * (desiredAngleROM - commandedAngle);
  }

  commandedAngle = clampFloat(commandedAngle, NORMAL_ROM_MIN_DEG, THERAPIST_MAX_ROM_DEG);
}

void sendMotorSmoothly() {
  if (systemFrozen) return;

  // Send every control update.
  // This makes the motor see a continuously moving target instead of separate points.
  sendPositionFast(commandedAngle);
  lastSentAngle = commandedAngle;
}

void checkScenario2Emergency() {
  if (supportMode == 1) {
    if (actualAngle > commandedAngle + COLLAPSE_ERROR_DEG) {
      freezeSystem(2);
    }
  }
}

// ============================================================
// SERIAL PLOTTER OUTPUT
// ============================================================
void printPlotterLine() {
  Serial.print(rawMLGaitPercent, 1);       Serial.print(",");
  Serial.print(usedGaitPercent, 1);        Serial.print(",");
  Serial.print(lookAheadGaitPercent, 1);   Serial.print(",");
  Serial.print(statusCode * 10);           Serial.print(",");
  Serial.print(desiredAngleNormal, 1);     Serial.print(",");
  Serial.print(desiredAngleROM, 1);        Serial.print(",");
  Serial.print(commandedAngle, 1);         Serial.print(",");
  Serial.print(actualAngle, 1);            Serial.print(",");
  Serial.print(badReading ? 20 : 0);       Serial.print(",");
  Serial.print(badReadingCounter * 5);     Serial.print(",");
  Serial.print(supportMode * 15);          Serial.print(",");
  Serial.println(systemFrozen ? 70 : 0);
}

// ============================================================
// SETUP
// ============================================================
void setup() {
  Serial.begin(115200);
  delay(3000);

  pinMode(BUZZER_PIN, OUTPUT);
  buzzerOff();

  MotorSerial.begin(115200, SERIAL_8N1, MOTOR_RX_PIN, MOTOR_TX_PIN);

  Serial.println("=== KNEVO ULTRA SMOOTH FSM + MOTOR ===");
  Serial.println("Ultra smooth mode: cubic interpolation + 4% look-ahead + command filter + 100Hz streaming");

  if (motorOn()) {
    Serial.println("Motor ON confirmed");
  } else {
    Serial.println("Motor ON failed");
  }

  // Initialize first target.
  rawMLGaitPercent = 0.0f;
  usedGaitPercent = 0.0f;
  updateSmoothFSMAndTrajectory(usedGaitPercent);

  sendPositionFast(commandedAngle);
  lastSentAngle = commandedAngle;

  delay(500);
  actualAngle = readActualAngleQuick();

  Serial.println("RawGait,UsedGait,LookAheadGait,State_x10,DesiredNormal_deg,DesiredROM_deg,Commanded_deg,Actual_deg,BadReading_x20,ErrorCount_x5,SupportMode_x15,Frozen_x70");
}

// ============================================================
// LOOP
// ============================================================
void loop() {
  unsigned long now = millis();

  // ----------------------------------------------------------
  // 1) CONTROL UPDATE: ultra smooth 100 Hz streaming
  // ----------------------------------------------------------
  if (now - lastControlTime >= CONTROL_MS) {
    lastControlTime = now;

    if (!systemFrozen) {
      rawMLGaitPercent = getGaitPercentInput();
      usedGaitPercent = validateOrPredictGait(rawMLGaitPercent);

      if (!systemFrozen) {
        updateSmoothFSMAndTrajectory(usedGaitPercent);
        sendMotorSmoothly();
      } else {
        commandedAngle = frozenAngle;
        supportMode = 2;
      }
    } else {
      buzzerOn();
    }
  }

  // ----------------------------------------------------------
  // 2) FEEDBACK UPDATE: slower so it does not break smoothness
  // ----------------------------------------------------------
  if (now - lastFeedbackTime >= FEEDBACK_MS) {
    lastFeedbackTime = now;
    actualAngle = readActualAngleQuick();

    if (!systemFrozen) {
      checkScenario2Emergency();
    }
  }

  // ----------------------------------------------------------
  // 3) SERIAL PLOTTER UPDATE
  // ----------------------------------------------------------
  if (now - lastPlotTime >= PLOT_MS) {
    lastPlotTime = now;
    printPlotterLine();
  }
}